### ISSUE TITLE
Add a direct shortcut without the need to open the panel.

### ISSUE THREAD

**Issue by gagarine** [belaviyo/keepass-macpass-helper#12]
It is possible to add a direct shortcut? Like ctr-maj-k / cmd-maj-k (k for key) that try to copy both password and login with auto-submit so I can quickly login without having to open the panel.

As I see it's supposed to be quiet easy https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

The logic can be like that:
if their is one texte field and a password field -> past both
if their is one texte field -> past username
if their is one password field -> past password
if their is more than two field -> past username in the current field, search for a password field and past the password 

So never never past password in a non password field without the user explicitly asking for it. We can have another shortcut to past the password if the current field btw. But I'm not sure it's really needed.

This can fix the need that was posted in #3

**Comment by belaviyo** [comment]
Okay so from the next release, there are two new options in the options page. You can ask the popup to automatically fill the login data and close itself. Also, you can request the form submission as well.

This only happens if there is a single credential available for the current page.

Note that using this method there is no need to define new commands. WebExtension is supposed to support custom commands and when it does, you can define a custom keyboard shortcut to open the toolbar panel. When these options are checked, both actions can be performed.

Currently, there is no support for custom keyboards in FF. You can try this on Chrome.
