### ISSUE TITLE
Don't use a panel in page

### ISSUE THREAD

**Issue by gagarine** [belaviyo/keepass-macpass-helper#9]
I think it would be cleaner to use a browser action pop-up instead of loading a panel in the browser page. A bit like dashlane or lastpass or others webextension are doing:

![screen shot 2017-08-12 at 12 16 49](https://user-images.githubusercontent.com/164074/29239838-5a1681ca-7f58-11e7-99fb-e0820941c1bb.png)

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction

**Comment by belaviyo** [comment]
It is possible but requires a lot of changes. I think the iframe method works pretty well for now. If you see any other issues with the current iframe method please report.

**Comment by gagarine** [comment]
I have to say I become use to it :).

**Comment by belaviyo** [comment]
No there is no way for the page to inject JS code to the iframe. The iframe has "extension://id" origin and since origins do not match, your browser does not allow interactions. You can try it yourself and see if you can access the DOM of the iframe from the page context.

**Comment by gagarine** [comment]
Perfect 
![screen shot 2017-08-20 at 12 53 33](https://user-images.githubusercontent.com/164074/29494261-99bfdfe8-85a6-11e7-985f-e37a29d68f2b.png)

**Comment by chris-morgan** [comment]
@gagarine That would never work anyway—#toolbar is inside an iframe, `document.getElementById` only searches inside the current document. You need something like this:

```js
document.querySelector('body>iframe:last-child').contentWindow.document.getElementById('toolbar')
```

You can get as far as `contentWindow`, but no further: “SecurityError: Permission denied to access property "document" on cross-origin object”

There’s no direct security risk to this, and in Firefox at least this bypasses CSP restrictions, but I’m still not comfortable with it modifying the page. The way you can open it multiple times at present and that keyboard focus and shortcuts are mildly screwy is the sort of thing that reinventing the wheel gets you—that’s a large part of the reason why you should use a WebExtensions popup.

**Comment by ty2u** [comment]
Hi there,

I was taking a look at this and regardless of if there's no security issue or not it's modifying the code of a website. I think this is a huge issue because the code on the website is not what the website expects it to be and this could and will cause unexpected issues on some pages, regardless of how rare it might be, it is possible. For example if a page expects a single iframe in it's javascript or CSS, etc. and then finds this plugin's iframe then there can be an issue with that because it could be attempting to modify the iframe expecting only their iframe but now there's an unexpected iframe on the page. You could argue that the javascript isn't necessarily well written then but that doesn't matter. This is bound to break the occasional page and cause the occasional issue.

It's similar to how some software running on computers like antiviruses such as Kaspersky would inject code into webpages. This causes issues and people dislike it. Eventually they added an option to disable that in the case of Kaspersky.

**Comment by belaviyo** [comment]
okay then we have two modes now in the options page. Either use the default embedded mode or use the popup mode.

Please give the dev version a try and let me know how it works
1. Download https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
2. Open "chrome://extensions/" and check "Developer mode"
3. Point the browser window to the root of the extracted archive

Please check the extension on both modes.

**Comment by belaviyo** [comment]
It is now FF compatible too (or I hope so). To try in FF:

1. Download https://github.com/belaviyo/keepass-macpass-helper/archive/master.zip
2. Open "about:debugging" and check "add-on debugging"
3. Point the "Load temporary add-on" to the root of the extracted archive -> manifest.json

**Comment by chris-morgan** [comment]
I confirm that it works in Firefox, both ways.

I hope that your intention now is to remove the embedded mode? I can’t think of any advantages of doing it that way, and the downsides are several and significant (as recorded already).

**Comment by belaviyo** [comment]
Yes, this is going to be the default mode though I am still supporting the iframe mode as well.
